# Generated by Django 5.0.1 on 2024-01-16 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protagonista',
            old_name='interpretacion',
            new_name='personaje',
        ),
    ]
