# Generated by Django 5.0.1 on 2024-01-16 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_interpretacion_protagonista_personaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.director'),
        ),
        migrations.DeleteModel(
            name='DirectorPelicula',
        ),
    ]
