# Generated by Django 5.0.1 on 2024-02-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pelicula_director_delete_directorpelicula'),
    ]

    operations = [
        migrations.AddField(
            model_name='protagonista',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
