# Generated by Django 5.0.1 on 2024-02-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_protagonista_nacionalidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protagonista',
            name='personaje',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='personaje',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
