# Generated by Django 5.0.1 on 2024-02-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pelicula_resumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='poster'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='resumen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
